# Generated by Django 3.0.3 on 2020-06-08 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='painting',
            old_name='Image',
            new_name='image',
        ),
    ]
