# Generated by Django 3.0.3 on 2020-06-08 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0002_auto_20200608_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='painting',
            old_name='image',
            new_name='Image',
        ),
    ]
