# Generated by Django 3.0.3 on 2020-04-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0004_painting'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='medium',
            field=models.CharField(default='Acrylic', max_length=264),
            preserve_default=False,
        ),
    ]
