# Generated by Django 3.0.3 on 2020-06-08 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0004_auto_20200608_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='painting',
            old_name='image',
            new_name='photo',
        ),
    ]
