# Generated by Django 3.0.3 on 2020-04-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0006_auto_20200413_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='paintings',
            field=models.ManyToManyField(related_name='paintings', to='Gallery.Painting'),
        ),
    ]
