# Generated by Django 3.0.3 on 2020-04-14 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gallery', '0007_auto_20200413_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='paintings',
            field=models.ManyToManyField(related_name='c_paintings', to='Gallery.Painting'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.BigIntegerField()),
                ('paintings', models.ManyToManyField(related_name='o_paintings', to='Gallery.Painting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
