# Generated by Django 3.0.3 on 2020-06-10 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gallery', '0007_auto_20200610_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='paintings',
            field=models.ManyToManyField(blank=True, related_name='c_paintings', to='Gallery.Painting'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
