# Generated by Django 3.0.3 on 2020-06-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0008_auto_20200610_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='sale',
            field=models.BooleanField(default=False),
        ),
    ]
