# Generated by Django 3.0.3 on 2020-04-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0009_auto_20200414_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bill',
            field=models.BigIntegerField(default=0),
        ),
    ]
