# Generated by Django 3.0.3 on 2020-04-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0010_auto_20200414_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('post', models.CharField(max_length=264)),
                ('image', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
