# Generated by Django 3.0.3 on 2020-04-15 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0011_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Member',
        ),
    ]
