# Generated by Django 3.0.3 on 2020-04-16 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0012_auto_20200415_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
    ]
