# Generated by Django 3.0.3 on 2020-06-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0013_remove_userprofile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uid',
            field=models.CharField(default='sdfgtyhuiol', max_length=264),
            preserve_default=False,
        ),
    ]
