# Generated by Django 3.0.3 on 2020-06-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0015_order_successful'),
    ]

    operations = [
        migrations.RenameField(
            model_name='painting',
            old_name='category',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='painting',
            name='medium',
        ),
        migrations.AddField(
            model_name='painting',
            name='description',
            field=models.TextField(default='dfd'),
            preserve_default=False,
        ),
    ]
