# Generated by Django 3.0.3 on 2020-06-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0016_auto_20200608_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='image',
            field=models.ImageField(default='media/anaya.jpg', upload_to='media/'),
        ),
    ]
